name: adaptive

channels:
- conda-forge

dependencies:
  - python=3.6
  - sortedcontainers
  - sortedcollections
  - scipy
  - holoviews
  - ipyparallel
  - distributed
  - ipykernel>=4.8*
  - jupyter_client>=5.2.2
  - ipywidgets
  - scikit-optimize
  - plotly
