name: adaptive-docs

channels:
  - conda-forge

dependencies:
  - python=3.10
  - sortedcollections=2.1.0
  - scipy=1.10.1
  - holoviews=1.18.3
  - bokeh=3.3.4
  - panel=1.3.8
  - pandas=2.0.0
  - plotly=5.14.1
  - ipywidgets=8.0.6
  - myst-nb=0.17.1
  - sphinx_fontawesome=0.0.6
  - sphinx=5.3.0
  - ffmpeg=5.1.2
  - cloudpickle=2.2.1
  - loky=3.3.0
  - furo=2023.3.27
  - myst-parser=0.18.1
  - dask=2024.2.0
  - emoji=2.2.0
  - versioningit=2.2.0
  - distributed=2024.2.0
  - param=2.0.2
