name: adaptive-docs

channels:
  - conda-forge

dependencies:
  - python=3.11.3
  - sortedcollections=2.1.0
  - scikit-optimize=0.9.0
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - holoviews=1.15.4
  - bokeh=2.4.3
  - panel=0.14.4
  - pandas=2.0.0
  - plotly=5.14.1
  - ipywidgets=8.0.6
  - myst-nb=0.17.1
  - sphinx_fontawesome=0.0.6
  - sphinx=5.3.0
  - ffmpeg=5.1.2
  - cloudpickle=2.2.1
  - loky=3.3.0
  - furo=2023.3.27
  - myst-parser=0.18.1
  - dask=2023.3.2
