name: adaptive

channels:
- conda-forge

dependencies:
  - python=3.7
  - pip:
    - sortedcollections
    - scipy
    - holoviews==1.12*
    - bokeh==1.1*
    - plotly
    - ipywidgets
    - scikit-optimize
    - git+https://github.com/basnijholt/jupyter-sphinx.git@widgets_execute
    - sphinx_fontawesome
    - m2r
