name: adaptive

channels:
- conda-forge

dependencies:
  - python=3.6
  - pip:
    - sortedcollections
    - scipy
    - holoviews==1.11
    - bokeh
    - plotly
    - ipyparallel
    - pandas  # until https://github.com/ioam/holoviews/issues/3430 is fixed
    - distributed
    - ipywidgets
    - scikit-optimize
    - git+https://github.com/basnijholt/jupyter-sphinx.git@widgets_execute
    - sphinx_fontawesome
    - m2r
